### ISSUE TITLE
Producer throws error when Scriptqueue config is not provided

### ISSUE THREAD

**Issue by jgalazm** [lsst-ts/LOVE-producer#13]
For this config.json
```json
{
  "ATSpectrograph": [
    {
      "index": 1,
      "source": "emitter"
    }
  ]
}
```

I'm seeing this error: 

```
love-producer-mount | # Setting up sal, salobj and scriptqueue
love-producer-mount | ***** Starting Producer *****
love-producer-mount | Reading config file:  /usr/src/love/config/config.json
love-producer-mount | Reading config file:  /usr/src/love/config/config.json
love-producer-mount | Traceback (most recent call last):
love-producer-mount |   File "/usr/src/love/main.py", line 135, in <module>
love-producer-mount |     sq_list = read_config(path, 'ScriptQueue')
love-producer-mount |   File "/usr/src/love/main.py", line 121, in read_config
love-producer-mount |     for csc_instance in data[key]:
love-producer-mount | KeyError: 'ScriptQueue'
love-producer-mount exited with code 1
```

There should be default values for the scriptqueue to handle this.

**Comment by sebastian-aranda** [comment]
This configuration is no longer used, we should remove the code related to this and close the issue.
