### ISSUE TITLE
Producer breaks in summit: code = 1006 (connection closed abnormally [internal]), no reason

### ISSUE THREAD

**Issue by jgalazm** [lsst-ts/LOVE-producer#68]
```
love-producer |     await self.write_frame(True, OP_PONG, data)
love-producer |   File "/opt/lsst/software/stack/python/miniconda3-4.7.10/envs/lsst-scipipe-4d7b902/lib/python3.7/site-packages/websockets/protocol.py", line 1083, in write_frame
love-producer |     await self.ensure_open()
love-producer |   File "/opt/lsst/software/stack/python/miniconda3-4.7.10/envs/lsst-scipipe-4d7b902/lib/python3.7/site-packages/websockets/protocol.py", line 803, in ensure_open
love-producer |     raise self.connection_closed_exc()
love-producer | websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
love-producer | 
love-producer | The above exception was the direct cause of the following exception:
love-producer | 
love-producer | Traceback (most recent call last):
love-producer |   File "/opt/lsst/software/stack/python/miniconda3-4.7.10/envs/lsst-scipipe-4d7b902/lib/python3.7/site-packages/websockets/protocol.py", line 555, in send
love-producer |     await self.ensure_open()
love-producer |   File "/opt/lsst/software/stack/python/miniconda3-4.7.10/envs/lsst-scipipe-4d7b902/lib/python3.7/site-packages/websockets/protocol.py", line 803, in ensure_open
love-producer |     raise self.connection_closed_exc()
love-producer | websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
love-producer | Task exception was never retrieved
love-producer | future: <Task finished coro=<WebSocketCommonProtocol.send() done, defined at /opt/lsst/software/stack/python/miniconda3-4.7.10/envs/lsst-scipipe-4d7b902/lib/python3.7/site-packages/websockets/protocol.py:521> exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), no reason')>
love-producer | Traceback (most recent call last):
love-producer |   File "/opt/lsst/software/stack/python/miniconda3-4.7.10/envs/lsst-scipipe-4d7b902/lib/python3.7/site-packages/websockets/protocol.py", line 827, in transfer_data
love-producer |     message = await self.read_message()
love-producer |   File "/opt/lsst/software/stack/python/miniconda3-4.7.10/envs/lsst-scipipe-4d7b902/lib/python3.7/site-packages/websockets/protocol.py", line 895, in read_message
love-producer |     frame = await self.read_data_frame(max_size=self.max_size)
love-producer |   File "/opt/lsst/software/stack/python/miniconda3-4.7.10/envs/lsst-scipipe-4d7b902/lib/python3.7/site-packages/websockets/protocol.py", line 995, in read_data_frame
love-producer |     await self.pong(frame.data)
love-producer |   File "/opt/lsst/software/stack/python/miniconda3-4.7.10/envs/lsst-scipipe-4d7b902/lib/python3.7/site-packages/websockets/protocol.py", line 770, in pong
love-producer |     await self.write_frame(True, OP_PONG, data)
love-producer |   File "/opt/lsst/software/stack/python/miniconda3-4.7.10/envs/lsst-scipipe-4d7b902/lib/python3.7/site-packages/websockets/protocol.py", line 1083, in write_frame
love-producer |     await self.ensure_open()
love-producer |   File "/opt/lsst/software/stack/python/miniconda3-4.7.10/envs/lsst-scipipe-4d7b902/lib/python3.7/site-packages/websockets/protocol.py", line 803, in ensure_open
love-producer |     raise self.connection_closed_exc()
love-producer | websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
love-producer | 
love-producer | The above exception was the direct cause of the following exception:
love-producer | 
love-producer | Traceback (most recent call last):
love-producer |   File "/opt/lsst/software/stack/python/miniconda3-4.7.10/envs/lsst-scipipe-4d7b902/lib/python3.7/site-packages/websockets/protocol.py", line 555, in send
love-producer |     await self.ensure_open()
love-producer |   File "/opt/lsst/software/stack/python/miniconda3-4.7.10/envs/lsst-scipipe-4d7b902/lib/python3.7/site-packages/websockets/protocol.py", line 803, in ensure_open
love-producer |     raise self.connection_closed_exc()
love-producer | websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
love-producer | Task exception was never retrieved
love-producer | future: <Task finished coro=<WebSocketCommonProtocol.send() done, defined at /opt/lsst/software/stack/python/miniconda3-4.7.10/envs/lsst-scipipe-4d7b902/lib/python3.7/site-packages/websockets/protocol.py:521> exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), no reason')>
love-producer | Traceback (most recent call last):
love-producer |   File "/opt/lsst/software/stack/python/miniconda3-4.7.10/envs/lsst-scipipe-4d7b902/lib/python3.7/site-packages/websockets/protocol.py", line 827, in transfer_data
love-producer |     message = await self.read_message()
love-producer |   File "/opt/lsst/software/stack/python/miniconda3-4.7.10/envs/lsst-scipipe-4d7b902/lib/python3.7/site-packages/websockets/protocol.py", line 895, in read_message
love-producer |     frame = await self.read_data_frame(max_size=self.max_size)
love-producer |   File "/opt/lsst/software/stack/python/miniconda3-4.7.10/envs/lsst-scipipe-4d7b902/lib/python3.7/site-packages/websockets/protocol.py", line 995, in read_data_frame
love-producer |     await self.pong(frame.data)
love-producer |   File "/opt/lsst/software/stack/python/miniconda3-4.7.10/envs/lsst-scipipe-4d7b902/lib/python3.7/site-packages/websockets/protocol.py", line 770, in pong
love-producer |     await self.write_frame(True, OP_PONG, data)
love-producer |   File "/opt/lsst/software/stack/python/miniconda3-4.7.10/envs/lsst-scipipe-4d7b902/lib/python3.7/site-packages/websockets/protocol.py", line 1083, in write_frame
love-producer |     await self.ensure_open()
love-producer |   File "/opt/lsst/software/stack/python/miniconda3-4.7.10/envs/lsst-scipipe-4d7b902/lib/python3.7/site-packages/websockets/protocol.py", line 803, in ensure_open
love-producer |     raise self.connection_closed_exc()
love-producer | websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
love-producer | 
love-producer | The above exception was the direct cause of the following exception:

```

**Comment by sebastian-aranda** [comment]
Resolved in future releases of the development env
